GET http://localhost:8080/accounts/minidooray

###

GET http://localhost:8080/accounts/kimsiyeon

###

GET http://localhost:8080/accounts
Content-Type: application/json

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
  "accountId": "minidooray",
  "password": "minidooray",
  "email": "minidooray@naver.com",
  "name": "두레이"
}

###

PATCH http://localhost:8080/accounts/minidooray
Content-Type: application/json

{
  "password": "minidooray",
  "email": "minidooray@gmail.com",
  "name": "미니두레이"
}

###

PATCH http://localhost:8080/accounts/kimsiyeon
Content-Type: application/json

{
  "password": "ksy",
  "email": "swanshawn715@gmail.com",
  "name": "시연"
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
  "accountId": "test",
  "password": "test",
  "email": "test@naver.com",
  "name": "imtest"
}