# Account

### kimsiyeon 조회
GET http://localhost:8888/accounts/kimsiyeon


### minidooray 조회
GET http://localhost:8888/accounts/minidooray


### "minidooray" 등록
POST http://localhost:8888/accounts
Content-Type: application/json

{
  "accountId": "minidooray",
  "password": "$2a$10$xnxIPORYILhbmjBmEbbNiu9UoH2u4ZJHuVbSfygRxmckFcO4l21Ee",
  "email": "minidooray@naver.com",
  "name": "두레이"
}


### minidooray 수정
PATCH http://localhost:8888/accounts/minidooray
Content-Type: application/json

{
  "password": "$2a$10$xnxIPORYILhbmjBmEbbNiu9UoH2u4ZJHuVbSfygRxmckFcO4l21Ee",
  "email": "minidooray@gmail.com",
  "name": "미니두레이"
}

### minidooray 자진 탈퇴
GET http://localhost:8888/accounts/withdraw/minidooray

### kimsiyeon 이름 변경 "김시연" -> "시연"
PATCH http://localhost:8888/accounts/kimsiyeon
Content-Type: application/json

{
  "password": "ksy",
  "email": "swanshawn715@gmail.com",
  "name": "시연"
}


### "test" 등록 / 비밀번호 길이 오류
POST http://localhost:8888/accounts
Content-Type: application/json

{
  "accountId": "test",
  "password": "test",
  "email": "test@naver.com",
  "name": "imtest"
}

###

# Admin

### 전체 회원 조회
GET http://localhost:8888/admin/accounts


### kimsiyeon 조회
GET http://localhost:8888/admin/accounts/kimsiyeon


### kimsiyeon을 휴면으로
PATCH http://localhost:8888/admin/accounts/kimsiyeon
Content-Type: application/json

{
  "statusCode": 3
}

### kimsiyeon을 강제탈퇴 -> 권한 없음
PATCH http://localhost:8888/admin/accounts/kimsiyeon
Content-Type: application/json

{
  "statusCode": 2
}