# Account

### kimsiyeon 조회
GET http://localhost:8888/accountapi/accounts/kimsiyeon


### minidooray 조회
GET http://localhost:8888/accountapi/accounts/minidooray

### 나를 뺀 전체 회원 조회
GET http://localhost:8888/accountapi/accounts/except/kimsiyeon

### "minidooray" 등록 오류
POST http://localhost:8888/accountapi/accounts
Content-Type: application/json

{
  "accountId": "minidooray",
  "password": "$2a$10$xnxIPORYILhbmjBmEbbNiu9UoH2u4ZJHuVbSfygRxmckFcO4l21Ee",
  "name": "두레이"
}

### "minidooray" 등록
POST http://localhost:8888/accountapi/accounts
Content-Type: application/json

{
  "accountId": "minidooray",
  "password": "$2a$10$xnxIPORYILhbmjBmEbbNiu9UoH2u4ZJHuVbSfygRxmckFcO4l21Ee",
  "email": "minidooray@naver.com",
  "name": "두레이"
}

### "minidooray" 비밀번호 오류
POST http://localhost:8888/accountapi/accounts
Content-Type: application/json

{
  "accountId": "minidooray",
  "password": "minidooraypassword",
  "email": "minidooray@naver.com",
  "name": "두레이"
}

### minidooray 메일, 이름 수정 오류
PATCH http://localhost:8888/accountapi/accounts/minidooray
Content-Type: application/json

{
  "email": "minidooray@gmail.com",
  "name": "미니두레이"
}

### minidooray 메일, 이름 수정 성공
PATCH http://localhost:8888/accountapi/accounts/minidooray
Content-Type: application/json

{
  "password": "$2a$10$xnxIPORYILhbmjBmEbbNiu9UoH2u4ZJHuVbSfygRxmckFcO4l21Ee",
  "email": "minidooray@gmail.com",
  "name": "미니두레이"
}

### minidooray 자진 탈퇴
GET http://localhost:8888/accountapi/accounts/withdraw/minidooray

### kimsiyeon 이름 변경 "김시연" -> "시연"
PATCH http://localhost:8888/accountapi/accounts/kimsiyeon
Content-Type: application/json

{
  "password": "$2a$10$2JrtuV13mUgKMNc6S25HVe0NX.q7vKlUpgQJi6WmYJ/B24XG7lp6S",
  "email": "swanshawn715@gmail.com",
  "name": "시연"
}


### "test" 등록 / 비밀번호 길이 오류
POST http://localhost:8888/accountapi/accounts
Content-Type: application/json

{
  "accountId": "test",
  "password": "test",
  "email": "test@naver.com",
  "name": "imtest"
}

###

# Admin

### 전체 회원 조회
GET http://localhost:8888/accountapi/admin/accounts


### kimsiyeon 조회
GET http://localhost:8888/accountapi/admin/accounts/kimsiyeon

### minidooray 조회
GET http://localhost:8888/accountapi/admin/accounts/minidooray

### kimsiyeon을 휴면으로
PATCH http://localhost:8888/accountapi/admin/accounts/kimsiyeon
Content-Type: application/json

{
  "statusCode": 3
}

### minidooray를 휴면으로
PATCH http://localhost:8888/accountapi/admin/accounts/minidooray
Content-Type: application/json

{
  "statusCode": 3
}

### kimsiyeon을 강제탈퇴 -> 권한 없음
PATCH http://localhost:8888/accountapi/admin/accounts/kimsiyeon
Content-Type: application/json

{
  "statusCode": 2
}

### minidooray를 휴면으로 (가입 x)
PATCH http://localhost:8888/accountapi/admin/accounts/minidooray
Content-Type: application/json

{
  "statusCode": 3
}

### 지정되지 않은 상태코드
PATCH http://localhost:8888/accountapi/admin/accounts/minidooray
Content-Type: application/json

{
  "statusCode": 10
}